version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./public:/var/www/html:cached
      - ./src:/var/www/src:cached
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=php-todo
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 80:80
  mysql:
    build: ./docker/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=php-todo
    ports:
      - 3306:3306
volumes:
  mysql-data:
    driver: local
